### PR TITLE
grammar fix

### PR DESCRIPTION
**Pull request by lsh-0**
'licence' is the noun, 'license' is the verb. Unless you're American.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
True. Does eLife has a policy on what flavo(u)r of English to use?

(You probably want to open this on the eLife repo, not my fork. And commit the result of `node compile.js` too.)

**Comment by lsh-0** [comment]
> True. Does eLife has a policy on what flavo(u)r of English to use?

do we need a policy to spell things correctly?

the eLife repo doesn't appear to have the article schema yet. am I mistaken
or is it still incoming?

On Sat, Jul 2, 2016 at 9:44 PM, Chris Wilkinson notifications@github.com
wrote:

> True. Does eLife has a policy on what flavo(u)r of English to use?
> 
> (You probably want to open this on the eLife repo, not my fork. And commit
> the result of node compile.js too.)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/thewilkybarkid/api-raml/pull/1#issuecomment-230121233,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACCyHHnS4kqEYEn5tvgzM200BvnmGEh8ks5qRs2XgaJpZM4JDtKp
> .

## 

Luke Skibinski

Formally defined,
Extensively tested,
Cryptic, abstract, thing.

## 

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.

**Comment by thewilkybarkid** [comment]
We show US-style dates. I suspect I copied it from JATS.

And yeah, correct about the repo. Was just keeping it as a PR until it's a bit more stable, but as the whole thing is a bit unstable until launch we could merge it.

**Comment by lsh-0** [comment]
> We show US-style dates.
> urgh, really? where? can't win them all, and I suppose we should have a
> certain amount of localisation going on for when we display things.
> 
> the whole thing is a bit unstable until launch we could merge it.
> I'd like to add validation the json being generated by the second scraper.
> I have a script that goes through all the articles and generates the
> article json now, some problems still but I'll talk to Giorgio about
> setting up a test pipeline for it

On Mon, Jul 4, 2016 at 1:10 PM, Chris Wilkinson notifications@github.com
wrote:

> We show US-style dates. I suspect I copied it from JATS.
> 
> And yeah, correct about the repo. Was just keeping it as a PR until it's a
> bit more stable, but as the whole thing is a bit unstable until launch we
> could merge it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/thewilkybarkid/api-raml/pull/1#issuecomment-230276238,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACCyHBG6wlkg9fEo9Q30UOEeIL0se1vQks5qSPgcgaJpZM4JDtKp
> .

## 

Luke Skibinski

Formally defined,
Extensively tested,
Cryptic, abstract, thing.

## 

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.

**Pull request closed without merging**
